use servdb;

--新會員-聯絡資訊
CREATE TABLE USERCONTACTNEW(
	CONTACTID INT IDENTITY(1001,1) NOT NULL PRIMARY KEY,
	USERNAME NVARCHAR(30)  NULL,
	USEREMAIL NVARCHAR(MAX)  NULL,
	USERPHONE NVARCHAR(10)  NULL,
	USERADDRESS NVARCHAR(MAX)  NULL
	
)
--新會員-基本資料
CREATE TABLE USERSNEW(
	USERID INT IDENTITY(1001,1) NOT NULL PRIMARY KEY ,
	FK_CONTACTID int not null,
	NICKNAME NVARCHAR(30)  NULL,
	GENDER NVARCHAR(1)  NULL,
	PASSWORD NVARCHAR(50) NOT NULL,
	BIRTHDAY DATE  NULL,
	USERPICTURE NVARCHAR(MAX) NULL,
	DANCECHARACTER NVARCHAR(20) NULL,
	DANCEAGE NVARCHAR(20) NULL,
	FOREIGN KEY (FK_CONTACTID) REFERENCES USERCONTACTNEW(CONTACTID)
)

select * from USERCONTACTNEW
select * from USERSNEW

drop table USERSNEW
drop table USERCONTACTNEW

--查詢Fk約束
SELECT name, OBJECT_NAME(parent_object_id) AS referencing_table
FROM sys.foreign_keys
WHERE referenced_object_id = OBJECT_ID('ORDER3');

