		CREATE TABLE LT(
			LTID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
			TITLE NVARCHAR(100) NOT NULL,
			USERID INT 
			FOREIGN KEY(USERID) REFERENCES DANCEUSER(IDUSER)
			ON DELETE SET NULL,
			DATE  DATETIME2 DEFAULT GETDATE() ,
			PICTURE NVARCHAR(100) NOT NULL,
			CONTENT TEXT NOT NULL,
		SAVELIKE INT DEFAULT 1		);	
	
CREATE TABLE REPLY(
    REPLYID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    REPLYTIME DATETIME2 DEFAULT GETDATE() ,
    REPLYPOST NVARCHAR(500) NOT NULL,
    USERID INT 
	FOREIGN KEY(USERID) REFERENCES DANCEUSER(IDUSER)
	ON DELETE SET NULL,
	
    LTID  INT ,
	FOREIGN KEY(LTID) REFERENCES LT(LTID)
	ON DELETE SET NULL
);
CREATE TABLE REPORTPOST(
REPORTID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
REPORTCONTENT NVARCHAR (500) NOT NULL,
LTID INT,
FOREIGN KEY(LTID) REFERENCES LT(LTID)
	ON DELETE SET NULL

)
CREATE TABLE REPORTREPLY(
REPORTREPLYID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
REPORTCONTENT NVARCHAR (500) NOT NULL,
REPLYID INT,
FOREIGN KEY(REPLYID) REFERENCES REPLY(REPLYID)
ON DELETE SET NULL
)

CREATE TABLE LIKEpost (
    LikeID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    UserID INT
	FOREIGN KEY(UserID) REFERENCES DANCEUSER(IDUSER),
   LTID INT 
   FOREIGN KEY (LTID)REFERENCES LT(LTID)
   ON DELETE SET NULL,
    CONSTRAINT UserArticle UNIQUE (UserID, LTID)
);



	CREATE TABLE DANCEUSER(

		IDUSER INT IDENTITY(1,1)  PRIMARY KEY,
		QQQ NVARCHAR(100)
	);

--檢舉留言
--案讚
--收藏


)
INSERT INTO REPORT(REPORTCONTENT,LTID) VALUES(1,1)
INSERT INTO REPORT(REPORTCONTENT,LTID) VALUES(1,2)
INSERT INTO REPORT(REPORTCONTENT,LTID) VALUES(1,3)

INSERT INTO REPLY (REPLYPOST, USERID,LTID) VALUES (3, 2,1 );[dbo].[DANCEUSE[dbo].[LT]R]
INSERT INTO REPLY (REPLYPOST, USERID) VALUES (3, 2 );
INSERT INTO REPLY (REPLYPOST, USERID) VALUES (3, 3 );
INSERT INTO REPLY (REPLYPOST, USERID) VALUES (3, 4);
INSERT INTO REPLY (REPLYPOST, USERID) VALUES (3, 5);

INSERT INTO DANCEUSER (QQQ) VALUES ('Value1');
INSERT INTO DANCEUSER (QQQ) VALUES ('Value2');
INSERT INTO DANCEUSER (QQQ) VALUES ('Value3');

	INSERT INTO LT (TITLE, DATE, PICTURE, CONTENT)
VALUES 
('Sample Title 1', GETDATE(), 'sample_picture1.jpg', 'Sample content 1'),
('Sample Title 2', GETDATE(), 'sample_picture2.jpg', 'Sample content 2'),
('Sample Title 3', GETDATE(), 'sample_picture3.jpg', 'Sample content 3'),
('Sample Title 4', GETDATE(), 'sample_picture4.jpg', 'Sample content 4'),
('Sample Title 5', GETDATE(), 'sample_picture5.jpg', 'Sample content 5');




SELECT * FROM LT
SELECT * FROM Reply
SELECT * FROM REPORTPOST
SELECT * FROM REPORTREPLY
SELECT * FROM LIKEPOST
SELECT * FROM DANCEUSER


	
DROP TABLE LT;
DROP TABLE REPORPOST
DROP TABLE REPLY;
DROP TABLE REPORTREPLY;
DROP TABLE likePOST;
DROP TABLE DANCEUSER;

INSERT INTO DANCEUSER (QQQ)
VALUES 
(8888)[dbo].[DANCEUSER]

SELECT * FROM LT WHERE title LIKE '%qq%';

SELECT ReplyId FROM Reply WHERE LTID =1
