CREATE TABLE EVENT(
PRODUCTID INT IDENTITY(300000,1) NOT NULL PRIMARY KEY,
EVENT_NAME NVARCHAR(50) NOT NULL, 
SIGNUP_STARTIME DATETIME2,
SIGNUP_ENDTIME DATETIME2,
EVENT_STARTIME DATETIME2,
EVENT_ENDTIME DATETIME2,
EVENT_DETAIL TEXT,
EVENT_CATEGORY NVARCHAR(MAX) NULL, --COURSE OR PARTY
EVENT_PRICE DECIMAL(10, 2) NOT NULL,
EVENT_ADDRES NVARCHAR(255) NOT NULL,
ORGANIZER NVARCHAR(MAX) NULL,
PICTURE NVARCHAR(MAX) NULL,

)

insert into EVENT values('Swing Rhythms','2023-02-08','2023-03-08','2023-04-08','2023-04-10','Program:BALBOA workshop with MELANIE & ALBERT',
'BALBOA','500','Big Apple studio 復興教室','Big Apple','fbxsb');
insert into EVENT values('Charleston Movement','2023-04-05','2023-05-05','2023-06-15','2023-06-17','Concert with THREE COOL CATS',
'LINDY','400','Asi幸福站','JFSwing','ergaga');
insert into EVENT values('Keep Punching','2023-05-20','2023-06-20','2023-06-27','2023-07-01','Herrang Dance Camp',
'LINDY','800','shita空間','JFSwing','rdthtb');
insert into EVENT values('Jazz Feet Weekend','2023-06-20','2023-07-20','2023-08-08','2023-08-11','Nathan&Meti&Andante',
'LINDY','700','西門紅樓','JFSwing','rqdeqedb');
insert into EVENT values('Live Band Foreast','2023-07-20','2023-08-20','2023-09-09','2023-09-11','Jhouse,Hopshbam DELUXE',
'LINDY','500','中山堂','JFSwing','fregerg');

select*from EVENT;


--VIEW跟資料庫內容是不同的


-- 前台會員管理訂單
CREATE TABLE USEREVENT (
	EVENTORDERID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,--訂單編號--pk
	ORDERTDATE DATE NOT NULL, -- 訂單日期 
	PRODUCTID INT NOT NULL CONSTRAINT EVENT_PRODUCTID_fk REFERENCES EVENT(PRODUCTID),--fk
	EVENT_NAME NVARCHAR(50) NOT NULL, --join
	EVENT_STARTIME DATETIME2,--join--活動名稱(join產生EVENT_NAME活動名稱EVENT_STARTIME活動日期)
	EVENT_PRICE DECIMAL(10, 2) NOT NULL, 
	ORDER_STATUS  NVARCHAR(20) NOT NULL DEFAULT'已付款',--訂單取消,請求審核中	
	--FK_IDUSER--會員編號
	IDUSER INT NOT NULL CONSTRAINT USEREVENT_IDUSER_fk REFERENCES users(IDUSER),--fk
	MAXIMUM INT,--報名上限
	SIGNEDUP_NUMBER INT, --已報名人數
)
	
	--EVENT_NAME NVARCHAR(50) NOT NULL, --join
	--EVENT_STARTIME DATETIME2,--join--活動名稱(join產生EVENT_NAME活動名稱EVENT_STARTIME活動日期)

select u.EVENTORDERID,u.ORDERTDATE ,u.PRODUCTID,e.EVENT_NAME,e.EVENT_STARTIME ,u.EVENT_PRICE,u.ORDER_STATUS,u.IDUSER
,u.MAXIMUM,u.SIGNEDUP_NUMBER
FROM EVENT e LEFT JOIN USEREVENT u ON e.EVENT_NAME = u.EVENT_NAME;


select*from USEREVENT;
drop table USEREVENT;


CREATE TABLE users(
IDUSER INT IDENTITY(1000,1) NOT NULL PRIMARY KEY,
username NVARCHAR(MAX) NOT NULL,
)
select*from users;
insert into users values('Mary');
insert into users values('Leo');
insert into users values('Jhon');

DROP TABLE users;

